"""End-to-end coverage for generated external integrations."""

import json
import subprocess
import sys
import time
import urllib.request
from urllib.parse import urlparse
from pathlib import Path

import psycopg2
import pytest
from dotenv import dotenv_values


MOCK_SCRIPT = Path("test-app/bin/dev-integration-odata-mock.py")
CALL_SCRIPT = Path("test-app/bin/dev-supabase-call-edge-function.py")


def _run(args, *, timeout=60, check=True):
    result = subprocess.run(args, capture_output=True, text=True, timeout=timeout)
    if result.stdout:
        print(result.stdout, end="")
    if result.stderr:
        print(result.stderr, end="", file=sys.stderr)
    if check:
        assert result.returncode == 0, f"command failed: {' '.join(map(str, args))}"
    return result


def _mock_command(action):
    return _run([sys.executable, str(MOCK_SCRIPT), action, str(_mock_port())])


def _mock_port():
    api_url = dotenv_values("test-app/backend/.env").get("SUPABASE_URL")
    assert api_url
    return urlparse(api_url).port - 29


def _wait_for_mock(timeout=10):
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        try:
            with urllib.request.urlopen(
                f"http://127.0.0.1:{_mock_port()}/mock/state", timeout=1
            ) as response:
                if response.status == 200:
                    return
        except OSError:
            time.sleep(0.1)
    raise AssertionError("OData mock did not become ready")


def _db_url():
    value = dotenv_values("test-app/backend/.env").get("DB_URL")
    assert value, "test-app must be generated and Supabase started by test_backend"
    return value


def _call_function(function, body='{"id": 1}'):
    result = _run([
        sys.executable,
        str(CALL_SCRIPT),
        "admin@test.com",
        function,
        body,
    ])
    return json.loads(result.stdout)


def _call_integration():
    return _call_function("integration-run")


@pytest.fixture(scope="module")
def odata_mock():
    assert MOCK_SCRIPT.exists(), "test-app must be generated by test_backend"
    _mock_command("--terminate")
    process = subprocess.Popen(
        [sys.executable, str(MOCK_SCRIPT), str(_mock_port())],
        stdout=subprocess.DEVNULL,
        stderr=subprocess.STDOUT,
    )
    try:
        _wait_for_mock()
        _mock_command("--reset")
        yield
    finally:
        _mock_command("--terminate")
        process.wait(timeout=10)


@pytest.mark.integration
@pytest.mark.timeout(120)
def test_manual_integration_and_incremental_polling(odata_mock):
    """The generated commands drive a full run and then one incremental change."""
    conn = psycopg2.connect(_db_url())
    try:
        with conn, conn.cursor() as cur:
            cur.execute(
                "SELECT id, name, schedule FROM _integration WHERE name = 'odata-companies'"
            )
            assert cur.fetchone() == (1, "odata-companies", "* * * * *")
            cur.execute(
                "SELECT jobid FROM cron.job WHERE jobname LIKE '\\_integration\\_%' ESCAPE '\\'"
            )
            for (job_id,) in cur.fetchall():
                cur.execute("SELECT cron.unschedule(%s)", (job_id,))
            cur.execute("DELETE FROM _integration_run")
            cur.execute("DELETE FROM external_company")
            cur.execute(
                "UPDATE _integration SET checkpoint = NULL, lease_owner = NULL, "
                "lease_expires_at = NULL, operational_status = 'active' WHERE id = 1"
            )

        first = _call_integration()
        assert first["status"] == 200
        assert first["body"]["status"] == "ok"
        assert first["body"]["data"]["received"] == 3

        with conn.cursor() as cur:
            cur.execute(
                "SELECT _external_id, name, city, active FROM external_company "
                "ORDER BY _external_id"
            )
            assert cur.fetchall() == [
                ("ES|1001", "Industrias Norte S.L.", "Bilbao", True),
                ("ES|1002", "Servicios Mediterraneo S.A.", "Valencia", True),
                ("PT|2001", "Comercio Atlantico Lda.", "Porto", True),
            ]

        advanced = json.loads(_mock_command("--advance").stdout)
        assert advanced["advanced"] is True
        second = _call_integration()
        assert second["status"] == 200
        assert second["body"]["data"]["received"] == 1

        with conn.cursor() as cur:
            cur.execute(
                "SELECT name, city FROM external_company WHERE _external_id = 'ES|1003'"
            )
            assert cur.fetchone() == ("Nueva Empresa S.A.", "Madrid")
            cur.execute(
                "SELECT status, received_count FROM _integration_run "
                "WHERE trigger = 'manual' ORDER BY requested_at"
            )
            assert cur.fetchall() == [("completed", 3), ("completed", 1)]

        for _ in range(2):
            assert json.loads(_mock_command("--advance").stdout)["advanced"] is True
            update = _call_integration()
            assert update["status"] == 200
            assert update["body"]["data"]["received"] == 1
            assert update["body"]["data"]["removed"] == 0

        assert json.loads(_mock_command("--advance").stdout)["advanced"] is True
        deletion = _call_integration()
        assert deletion["status"] == 200
        assert deletion["body"]["data"]["received"] == 0
        assert deletion["body"]["data"]["removed"] == 1

        with conn.cursor() as cur:
            cur.execute(
                "SELECT active FROM external_company WHERE _external_id = 'PT|2001'"
            )
            assert cur.fetchone() == (False,)
            cur.execute(
                "SELECT received_count, removed_count FROM _integration_run "
                "WHERE trigger = 'manual' ORDER BY requested_at"
            )
            assert cur.fetchall() == [(3, 0), (1, 0), (1, 0), (1, 0), (0, 1)]

            cur.execute("SELECT checkpoint FROM _integration WHERE id = 1")
            checkpoint_before_reset = cur.fetchone()[0]
            assert checkpoint_before_reset is not None
            cur.execute(
                "UPDATE _integration SET lease_owner = 'test-running', "
                "lease_expires_at = now() + interval '5 minutes' WHERE id = 1"
            )
        conn.commit()

        blocked_reset = _call_function("integration-reset-checkpoint")
        assert blocked_reset["status"] == 200
        assert blocked_reset["body"] == {
            "status": "ko",
            "message": "One or more integrations are running or do not exist",
        }
        with conn, conn.cursor() as cur:
            cur.execute("SELECT checkpoint FROM _integration WHERE id = 1")
            assert cur.fetchone()[0] == checkpoint_before_reset
            cur.execute(
                "UPDATE _integration SET lease_owner = NULL, lease_expires_at = NULL WHERE id = 1"
            )

        reset = _call_function("integration-reset-checkpoint")
        assert reset["status"] == 200
        assert reset["body"] == {
            "status": "ok",
            "message": "Checkpoint reset for odata-companies",
        }
        with conn.cursor() as cur:
            cur.execute("SELECT checkpoint, lease_owner, lease_expires_at FROM _integration WHERE id = 1")
            assert cur.fetchone() == (None, None, None)

        complete_reload = _call_integration()
        assert complete_reload["status"] == 200
        assert complete_reload["body"]["status"] == "ok"
        assert complete_reload["body"]["data"]["received"] == 3
        assert complete_reload["body"]["data"]["removed"] == 1
    finally:
        with conn, conn.cursor() as cur:
            cur.execute("SELECT public._reconcile_integration_cron()")
        conn.close()


@pytest.mark.integration
@pytest.mark.timeout(100)
def test_scheduled_integration_when_slow(request, odata_mock):
    """Optionally wait for pg_cron to invoke the real integration endpoint."""
    if not request.config.getoption("--slow"):
        pytest.skip("requires --slow to wait for the next minute boundary")

    conn = psycopg2.connect(_db_url())
    try:
        with conn.cursor() as cur:
            cur.execute(
                "SELECT jobname, schedule FROM cron.job WHERE jobname = '_integration_odata-companies'"
            )
            assert cur.fetchone() == ("_integration_odata-companies", "* * * * *")
            cur.execute("SELECT clock_timestamp()")
            started_at = cur.fetchone()[0]

        deadline = time.monotonic() + 75
        last = None
        while time.monotonic() < deadline:
            with conn.cursor() as cur:
                cur.execute(
                    "SELECT status, error FROM _integration_run "
                    "WHERE trigger = 'scheduled' AND requested_at >= %s "
                    "ORDER BY requested_at DESC LIMIT 1",
                    (started_at,),
                )
                last = cur.fetchone()
            if last and last[0] == "completed":
                return
            time.sleep(1)
        raise AssertionError(f"No completed scheduled integration within 75 seconds; last={last}")
    finally:
        conn.close()
