import React, { useState, useEffect, useMemo } from 'react';
import { useSearchParams } from 'react-router-dom';
import MDEditor from '@uiw/react-md-editor';
import { supabaseClient } from '../../supabaseClient';
import { useSession, publicUrl } from '../lib';

// ---------------------------------------------------------------------------
// Company News — public news site. Published articles are readable without a
// session (the `_anon` read rules), covers are served from the public
// `article-documents` bucket, and the markdown body is rendered with the same
// editor package the generated admin uses. Staff manage content in the
// generated React-Admin backoffice at #/admin.
// ---------------------------------------------------------------------------

const ACCENT = '#0f766e';
const ACCENT_2 = '#14b8a6';
const INK = '#1e293b';
const MUTED = '#64748b';
const BORDER = '#e2e8f0';
const FONT = '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif';

export default function NewsHome() {
  const [searchParams, setSearchParams] = useSearchParams();
  const session = useSession(); // undefined = loading, null = signed out
  const [categories, setCategories] = useState([]);
  const [selectedCategory, setSelectedCategory] = useState(null);
  const [articles, setArticles] = useState(null); // null = loading

  useEffect(() => {
    supabaseClient
      .from('category')
      .select('id, name')
      .order('name')
      .then(({ data }) => setCategories(data ?? []));
  }, []);

  useEffect(() => {
    supabaseClient
      .from('article')
      .select(
        'id, title, summary, body, category, published_date, is_featured, ' +
        'article_document(tag, storage_path)'
      )
      .eq('status', 'published')
      .order('published_date', { ascending: false, nullsFirst: false })
      .then(({ data }) => setArticles(data ?? []));
  }, []);

  const categoryNames = useMemo(
    () => Object.fromEntries(categories.map((c) => [c.id, c.name])),
    [categories]
  );

  const readingId = searchParams.get('read');
  const reading = readingId
    ? (articles ?? []).find((a) => String(a.id) === readingId)
    : null;

  const featured = (articles ?? []).find((a) => a.is_featured) ?? (articles ?? [])[0];
  const rest = (articles ?? []).filter(
    (a) => selectedCategory == null || a.category === selectedCategory
  );

  const openArticle = (id) => setSearchParams({ read: String(id) });
  const closeArticle = () => setSearchParams({});

  return (
    <div style={{ fontFamily: FONT, color: INK, minHeight: '100vh', background: '#fff' }}>
      <Header session={session} />

      <main style={{ maxWidth: 1080, margin: '0 auto', padding: '0 20px 80px' }}>
        {reading ? (
          <Reader
            article={reading}
            categoryName={categoryNames[reading.category]}
            onBack={closeArticle}
          />
        ) : articles === null ? (
          <Centered>Loading news…</Centered>
        ) : articles.length === 0 ? (
          <Centered>No published articles yet.</Centered>
        ) : (
          <>
            {featured && (
              <FeaturedCard
                article={featured}
                categoryName={categoryNames[featured.category]}
                onOpen={() => openArticle(featured.id)}
              />
            )}

            <div style={{ display: 'flex', gap: 10, marginTop: 30, flexWrap: 'wrap' }}>
              <Chip label="All" active={selectedCategory == null} onClick={() => setSelectedCategory(null)} />
              {categories.map((c) => (
                <Chip key={c.id} label={c.name} active={selectedCategory === c.id}
                  onClick={() => setSelectedCategory(c.id)} />
              ))}
            </div>

            {rest.length === 0 ? (
              <Centered>No articles in this category.</Centered>
            ) : (
              <div style={{
                display: 'grid',
                gridTemplateColumns: 'repeat(auto-fill, minmax(280px, 1fr))',
                gap: 24, marginTop: 24,
              }}>
                {rest.map((a) => (
                  <ArticleCard key={a.id} article={a}
                    categoryName={categoryNames[a.category]}
                    onOpen={() => openArticle(a.id)} />
                ))}
              </div>
            )}
          </>
        )}
      </main>

      <footer style={{
        borderTop: `1px solid ${BORDER}`, padding: '18px 20px', textAlign: 'center',
        color: MUTED, fontSize: 13,
      }}>
        Company News — generated by UniBizKit
      </footer>
    </div>
  );
}

// ===========================================================================
// Header
// ===========================================================================

function Header({ session }) {
  return (
    <header style={{
      position: 'sticky', top: 0, zIndex: 20, background: 'rgba(255,255,255,0.92)',
      backdropFilter: 'blur(8px)', borderBottom: `1px solid ${BORDER}`,
    }}>
      <div style={{
        maxWidth: 1080, margin: '0 auto', padding: '14px 20px',
        display: 'flex', alignItems: 'center', justifyContent: 'space-between',
      }}>
        <a href="#/" style={{
          display: 'flex', alignItems: 'center', gap: 10, fontWeight: 800, fontSize: 20,
          color: INK, textDecoration: 'none',
        }}>
          <span style={{
            display: 'inline-flex', width: 32, height: 32, borderRadius: 9,
            background: `linear-gradient(135deg, ${ACCENT}, ${ACCENT_2})`, color: '#fff',
            alignItems: 'center', justifyContent: 'center', fontSize: 18,
          }}>📰</span>
          Company News
        </a>
        <div style={{ display: 'flex', gap: 16, alignItems: 'center', fontSize: 14 }}>
          {session ? (
            <>
              <a href="#/admin" style={{ color: ACCENT, fontWeight: 600, textDecoration: 'none' }}>
                Newsroom
              </a>
              <span onClick={() => supabaseClient.auth.signOut()}
                style={{ cursor: 'pointer', color: MUTED }}>Sign out</span>
            </>
          ) : (
            <a href="#/admin" style={{
              color: '#fff', background: ACCENT, padding: '8px 16px', borderRadius: 999,
              fontWeight: 600, textDecoration: 'none',
            }}>Staff sign in</a>
          )}
        </div>
      </div>
    </header>
  );
}

// ===========================================================================
// Cards
// ===========================================================================

function coverUrl(article) {
  const docs = article.article_document ?? [];
  const byTag = (tag) => docs.find((d) => d.tag === tag);
  const cover = byTag('img_m') ?? byTag('img_l') ?? byTag('img_s');
  return publicUrl('article-documents', cover?.storage_path);
}

function formatDate(iso) {
  if (!iso) return '';
  return new Date(iso).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
}

function CategoryTag({ name }) {
  if (!name) return null;
  return (
    <span style={{
      display: 'inline-block', padding: '3px 10px', borderRadius: 999, fontSize: 12,
      fontWeight: 700, background: '#f0fdfa', color: ACCENT, border: `1px solid #ccfbf1`,
    }}>{name}</span>
  );
}

function FeaturedCard({ article, categoryName, onOpen }) {
  const img = coverUrl(article);
  return (
    <section onClick={onOpen} style={{
      marginTop: 28, borderRadius: 20, overflow: 'hidden', cursor: 'pointer',
      border: `1px solid ${BORDER}`, display: 'grid',
      gridTemplateColumns: 'minmax(280px, 5fr) 7fr', minHeight: 300,
      boxShadow: '0 10px 30px rgba(15,23,42,0.08)',
    }}>
      <div style={{
        background: img
          ? `url(${img}) center/cover no-repeat`
          : `linear-gradient(135deg, ${ACCENT}, ${ACCENT_2})`,
        minHeight: 240,
      }} />
      <div style={{ padding: '36px 40px', display: 'flex', flexDirection: 'column', justifyContent: 'center' }}>
        <div style={{ display: 'flex', gap: 10, alignItems: 'center' }}>
          <CategoryTag name={categoryName} />
          <span style={{ color: MUTED, fontSize: 13 }}>{formatDate(article.published_date)}</span>
        </div>
        <h1 style={{ margin: '14px 0 10px', fontSize: 32, lineHeight: 1.15, fontWeight: 800 }}>
          {article.title}
        </h1>
        {article.summary && (
          <p style={{ margin: 0, color: MUTED, fontSize: 16, lineHeight: 1.6 }}>{article.summary}</p>
        )}
        <span style={{ marginTop: 18, color: ACCENT, fontWeight: 700, fontSize: 15 }}>
          Read the story →
        </span>
      </div>
    </section>
  );
}

function ArticleCard({ article, categoryName, onOpen }) {
  const img = coverUrl(article);
  return (
    <article onClick={onOpen} style={{
      border: `1px solid ${BORDER}`, borderRadius: 16, overflow: 'hidden',
      cursor: 'pointer', background: '#fff', display: 'flex', flexDirection: 'column',
      transition: 'box-shadow .15s',
    }}
      onMouseEnter={(e) => { e.currentTarget.style.boxShadow = '0 12px 28px rgba(15,23,42,0.12)'; }}
      onMouseLeave={(e) => { e.currentTarget.style.boxShadow = 'none'; }}
    >
      <div style={{
        aspectRatio: '16 / 9',
        background: img
          ? `url(${img}) center/cover no-repeat`
          : `linear-gradient(135deg, ${ACCENT}, ${ACCENT_2})`,
      }} />
      <div style={{ padding: '16px 18px 20px' }}>
        <div style={{ display: 'flex', gap: 10, alignItems: 'center' }}>
          <CategoryTag name={categoryName} />
          <span style={{ color: MUTED, fontSize: 12 }}>{formatDate(article.published_date)}</span>
        </div>
        <h2 style={{ margin: '10px 0 6px', fontSize: 19, lineHeight: 1.3, fontWeight: 700 }}>
          {article.title}
        </h2>
        {article.summary && (
          <p style={{
            margin: 0, color: MUTED, fontSize: 14, lineHeight: 1.55,
            display: '-webkit-box', WebkitLineClamp: 3, WebkitBoxOrient: 'vertical', overflow: 'hidden',
          }}>{article.summary}</p>
        )}
      </div>
    </article>
  );
}

// ===========================================================================
// Reader — full article with the markdown body rendered
// ===========================================================================

function Reader({ article, categoryName, onBack }) {
  const img = coverUrl(article);
  return (
    <div style={{ maxWidth: 760, margin: '0 auto' }}>
      <button onClick={onBack} style={{
        margin: '24px 0 0', padding: '8px 16px', borderRadius: 999, cursor: 'pointer',
        border: `1px solid ${BORDER}`, background: '#fff', color: INK, fontWeight: 600, fontSize: 14,
      }}>← All news</button>

      {img && (
        <div style={{
          marginTop: 22, borderRadius: 16, aspectRatio: '21 / 9',
          background: `url(${img}) center/cover no-repeat`,
        }} />
      )}

      <div style={{ display: 'flex', gap: 10, alignItems: 'center', marginTop: 26 }}>
        <CategoryTag name={categoryName} />
        <span style={{ color: MUTED, fontSize: 13 }}>{formatDate(article.published_date)}</span>
      </div>
      <h1 style={{ margin: '12px 0 6px', fontSize: 36, lineHeight: 1.15, fontWeight: 800 }}>
        {article.title}
      </h1>
      {article.summary && (
        <p style={{ margin: '6px 0 0', color: MUTED, fontSize: 17, lineHeight: 1.6 }}>{article.summary}</p>
      )}

      <div data-color-mode="light" style={{ marginTop: 28 }}>
        <MDEditor.Markdown source={article.body ?? ''} style={{ fontSize: 16, lineHeight: 1.7 }} />
      </div>
    </div>
  );
}

// ===========================================================================
// Small helpers
// ===========================================================================

function Chip({ label, active, onClick }) {
  return (
    <button onClick={onClick} style={{
      padding: '8px 16px', borderRadius: 999, cursor: 'pointer', fontSize: 14, fontWeight: 600,
      border: `1px solid ${active ? ACCENT : BORDER}`,
      background: active ? ACCENT : '#fff', color: active ? '#fff' : INK,
      transition: 'all .15s',
    }}>{label}</button>
  );
}

function Centered({ children }) {
  return (
    <div style={{ padding: '70px 0', textAlign: 'center', color: MUTED, fontSize: 15 }}>
      {children}
    </div>
  );
}
