"""Shared fragments for the generated default auth pages.

The visual primitives live in presentation/style/auth.jsx (overridable per
model, see style/auth.py); pages import them so a model rebrand reaches every
auth page without touching their logic.
"""

UI_IMPORT = (
    "import { INK, MUTED, BORDER, ACCENT, BG, FONT, Card, Field, Message, SubmitButton } "
    "from '../style/auth';"
)


def header(title: str) -> str:
    return f"""// ---------------------------------------------------------------------------
// {title} — generated by UniBizKit.
// Look & feel comes from ../style/auth (override presentation/style/auth.jsx
// in your model to rebrand every auth page at once). For structural redesigns,
// copy this file into the model's presentation/pages/ (same file name): the
// model's copy replaces this generated default. It uses only React,
// react-router and the presentation lib (../lib), so it keeps working across
// react-admin/MUI upgrades. Lib calls return data and throw Error with a
// user-displayable message — render errors wherever suits your design (this
// page shows them inline in the form).
// ---------------------------------------------------------------------------
"""
