import re
from .context import Context
from .. import dev_ports
from ..dev_sso.constants import REALM_NAME


def generate(ctx: Context) -> str:
    system_config = ctx.system_config
    smtp = system_config.get('smtp', {})
    smtp_host = smtp.get('host', '127.0.0.1')
    if smtp_host in ('127.0.0.1', 'localhost'):
        smtp_host = '172.17.0.1'
        smtp_port = dev_ports.SMTP
    else:
        smtp_port = smtp.get('port', 25)
    smtp_from = smtp.get('from_email', 'noreply@localhost')

    base_uri = ctx.deployment_config.get('base_uri', '/')
    # base_uri always ends with / (normalized by SchemaProcessor)
    # site_url keeps the trailing slash so Supabase redirect_to matches Vite's base exactly
    base_url = f'http://localhost:{dev_ports.FRONTEND}{base_uri}'
    # external_url routes email links through the Vite dev proxy
    base_prefix = base_uri.rstrip('/')
    api_external_url = f'http://localhost:{dev_ports.FRONTEND}{base_prefix}/api'

    registration = ctx.security_config['registration']
    allow_registration = registration['allow']
    enable_signup = 'true' if allow_registration else 'false'

    app_name = ctx.business_schema.get('name', 'app')
    project_id = re.sub(r'[^a-z0-9]+', '_', app_name.lower()).strip('_')
    project_id = f"{project_id}_{dev_ports.ENV_NUM:02d}"

    return f"""# Changes to apply on top of the config.toml generated by "supabase init".
# Applied automatically by bin/dev-supabase-start.py.
project_id = "{project_id}"

[api]
port = {dev_ports.SUPABASE_API}
external_url = "{api_external_url}"

[db]
port = {dev_ports.SUPABASE_DB}
shadow_port = {dev_ports.SUPABASE_SHADOW}

[db.pooler]
port = {dev_ports.SUPABASE_POOLER}

[db.seed]
enabled = true
sql_paths = ["./seed.sql"]

[studio]
port = {dev_ports.SUPABASE_STUDIO}

[inbucket]
port = {dev_ports.SUPABASE_INBUCKET}

[analytics]
port = {dev_ports.SUPABASE_ANALYTICS}

[edge_runtime]
inspector_port = {dev_ports.EDGE_INSPECTOR}

""" + ("""
[functions.integration-run]
verify_jwt = false
""" if ctx.integrations_config["integrations"] else "") + f"""

[auth]
site_url = "{base_url}"
additional_redirect_urls = ["{base_url}", "{base_url.rstrip('/')}/**"]
enable_signup = {enable_signup}

[auth.rate_limit]
email_sent = 120

[auth.email]
# Must stay true even when registration is disabled: this flag toggles the whole
# email provider in GoTrue (false = no password logins at all, even for existing
# users). Blocking self-registration is handled by [auth] enable_signup above.
enable_signup = true
enable_confirmations = true
max_frequency = "1s"

[auth.email.smtp]
enabled = true
host = "{smtp_host}"
port = {smtp_port}
admin_email = "{smtp_from}"
sender_name = "App"
""" + (f"""
[auth.external.keycloak]
enabled = true
client_id = "supabase"
secret = "REPLACE_WITH_DEV_SSO_SECRET"
url = "http://keycloak.dev.local:{dev_ports.KC_PORT}/realms/{REALM_NAME}"
""" if ctx.security_config["sso"]["enabled"] else "") + """
[auth.hook.custom_access_token]
enabled = true
uri = "pg-functions://postgres/public/custom_access_token_hook"
"""
