from .constants import REGISTRY


def generate(ctx) -> str:
    """Compose template deployed to ~/ubk/<app>/docker-compose-<version>.yml.

    bin/prod-publish.py replaces __VERSION__; ${VARS} are resolved by
    docker-compose from the .env file next to the compose file on the remote
    host (secrets and PUBLIC_HOST, written on first publish). Compose file
    format 2.4: supported by both docker-compose 1.x and the compose v2
    plugin, and allows depends_on conditions on healthchecks.
    """
    app = ctx.app_id
    site_url = f"http://${{PUBLIC_HOST}}:{ctx.frontend_port}{ctx.base_uri}"
    api_external_url = f"http://${{PUBLIC_HOST}}:{ctx.frontend_port}{ctx.base_prefix}/api"
    disable_signup = "false" if ctx.allow_registration else "true"
    if ctx.smtp:
        mailer = f"""\
      GOTRUE_MAILER_AUTOCONFIRM: "false"
      GOTRUE_SMTP_HOST: {ctx.smtp['host']}
      GOTRUE_SMTP_PORT: {ctx.smtp.get('port', 25)}
      GOTRUE_SMTP_USER: {ctx.smtp.get('user', '')}
      GOTRUE_SMTP_PASS: {ctx.smtp.get('password', '')}
      GOTRUE_SMTP_ADMIN_EMAIL: {ctx.smtp.get('from_email', 'noreply@localhost')}
      GOTRUE_SMTP_SENDER_NAME: App"""
    else:
        mailer = '      GOTRUE_MAILER_AUTOCONFIRM: "true"'

    return f"""\
# Production stack for {app}, version __VERSION__ (immutable).
# Generated by UniBizKit; deployed by bin/prod-dc-up.py. Secrets come from the
# .env file in this directory. Data lives in the db-data / storage-data
# volumes and survives version switches.
version: "2.4"

services:
  db:
    image: {REGISTRY}/{app}/db:__VERSION__
    restart: unless-stopped
    command:
      - postgres
      - -c
      - config_file=/etc/postgresql/postgresql.conf
      - -c
      - log_min_messages=warning
    ports:
      - "{ctx.db_port}:5432"
    environment:
      POSTGRES_HOST: /var/run/postgresql
      PGPORT: "5432"
      POSTGRES_PORT: "5432"
      PGDATABASE: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: ${{POSTGRES_PASSWORD}}
      PGPASSWORD: ${{POSTGRES_PASSWORD}}
      JWT_SECRET: ${{JWT_SECRET}}
      JWT_EXP: "3600"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      # Generous: the first boot initializes the whole cluster on VM-grade hardware.
      retries: 60
      start_period: 30s

  auth:
    image: {REGISTRY}/{app}/vendor/gotrue:__VERSION__
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      GOTRUE_API_HOST: 0.0.0.0
      GOTRUE_API_PORT: "9999"
      API_EXTERNAL_URL: {api_external_url}
      GOTRUE_DB_DRIVER: postgres
      GOTRUE_DB_DATABASE_URL: postgres://supabase_auth_admin:${{POSTGRES_PASSWORD}}@db:5432/postgres
      GOTRUE_SITE_URL: {site_url}
      GOTRUE_URI_ALLOW_LIST: {site_url},{site_url.rstrip('/')}/**
      GOTRUE_DISABLE_SIGNUP: "{disable_signup}"
      GOTRUE_JWT_ADMIN_ROLES: service_role
      GOTRUE_JWT_AUD: authenticated
      GOTRUE_JWT_DEFAULT_GROUP_NAME: authenticated
      GOTRUE_JWT_EXP: "3600"
      GOTRUE_JWT_SECRET: ${{JWT_SECRET}}
      GOTRUE_EXTERNAL_EMAIL_ENABLED: "true"
{mailer}
      GOTRUE_HOOK_CUSTOM_ACCESS_TOKEN_ENABLED: "true"
      GOTRUE_HOOK_CUSTOM_ACCESS_TOKEN_URI: pg-functions://postgres/public/custom_access_token_hook
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9999/health"]
      interval: 5s
      timeout: 5s
      retries: 20

  rest:
    image: {REGISTRY}/{app}/vendor/postgrest:__VERSION__
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      PGRST_DB_URI: postgres://authenticator:${{POSTGRES_PASSWORD}}@db:5432/postgres
      PGRST_DB_SCHEMAS: public,storage
      PGRST_DB_ANON_ROLE: anon
      PGRST_JWT_SECRET: ${{JWT_SECRET}}
      PGRST_DB_USE_LEGACY_GUCS: "false"
      PGRST_APP_SETTINGS_JWT_SECRET: ${{JWT_SECRET}}
      PGRST_APP_SETTINGS_JWT_EXP: "3600"

  storage:
    image: {REGISTRY}/{app}/vendor/storage-api:__VERSION__
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      rest:
        condition: service_started
    environment:
      ANON_KEY: ${{ANON_KEY}}
      SERVICE_KEY: ${{SERVICE_ROLE_KEY}}
      POSTGREST_URL: http://rest:3000
      PGRST_JWT_SECRET: ${{JWT_SECRET}}
      DATABASE_URL: postgres://supabase_storage_admin:${{POSTGRES_PASSWORD}}@db:5432/postgres
      FILE_SIZE_LIMIT: "52428800"
      STORAGE_BACKEND: file
      FILE_STORAGE_BACKEND_PATH: /var/lib/storage
      TENANT_ID: stub
      REGION: stub
      GLOBAL_S3_BUCKET: stub
      ENABLE_IMAGE_TRANSFORMATION: "false"
    volumes:
      - storage-data:/var/lib/storage
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/status"]
      interval: 5s
      timeout: 5s
      retries: 20

  functions:
    image: {REGISTRY}/{app}/functions:__VERSION__
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    command:
      - start
      - --main-service
      - /home/deno/functions/main
    environment:
      JWT_SECRET: ${{JWT_SECRET}}
      SUPABASE_URL: http://kong:8000
      SUPABASE_ANON_KEY: ${{ANON_KEY}}
      SUPABASE_SERVICE_ROLE_KEY: ${{SERVICE_ROLE_KEY}}
      SUPABASE_DB_URL: postgresql://postgres:${{POSTGRES_PASSWORD}}@db:5432/postgres
      VERIFY_JWT: "false"

  kong:
    image: {REGISTRY}/{app}/kong:__VERSION__
    restart: unless-stopped
    # Substitute $SUPABASE_ANON_KEY / $SUPABASE_SERVICE_KEY into the declarative
    # config at startup (same mechanism as the official Supabase self-hosting compose).
    entrypoint: bash -c 'eval "echo \\"$$(cat ~/temp.yml)\\"" > ~/kong.yml && /docker-entrypoint.sh kong docker-start'
    depends_on:
      - auth
      - rest
      - storage
      - functions
    ports:
      - "{ctx.kong_port}:8000"
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /home/kong/kong.yml
      KONG_DNS_ORDER: LAST,A,CNAME
      KONG_PLUGINS: request-transformer,cors,key-auth,acl
      KONG_NGINX_PROXY_PROXY_BUFFER_SIZE: 160k
      KONG_NGINX_PROXY_PROXY_BUFFERS: 64 160k
      SUPABASE_ANON_KEY: ${{ANON_KEY}}
      SUPABASE_SERVICE_KEY: ${{SERVICE_ROLE_KEY}}

  frontend:
    image: {REGISTRY}/{app}/frontend:__VERSION__
    restart: unless-stopped
    depends_on:
      - kong
    ports:
      - "{ctx.frontend_port}:80"

  meta:
    image: {REGISTRY}/{app}/vendor/postgres-meta:__VERSION__
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      PG_META_PORT: "8080"
      PG_META_DB_HOST: db
      PG_META_DB_PORT: "5432"
      PG_META_DB_NAME: postgres
      PG_META_DB_USER: postgres
      PG_META_DB_PASSWORD: ${{POSTGRES_PASSWORD}}

  # Supabase Studio (admin UI), exposed on the studio port (base + 43).
  studio:
    image: {REGISTRY}/{app}/vendor/studio:__VERSION__
    restart: unless-stopped
    depends_on:
      - meta
      - kong
    ports:
      - "{ctx.studio_port}:3000"
    environment:
      STUDIO_PG_META_URL: http://meta:8080
      POSTGRES_PASSWORD: ${{POSTGRES_PASSWORD}}
      SUPABASE_URL: http://kong:8000
      SUPABASE_PUBLIC_URL: {api_external_url}
      AUTH_JWT_SECRET: ${{JWT_SECRET}}
      SUPABASE_ANON_KEY: ${{ANON_KEY}}
      SUPABASE_SERVICE_KEY: ${{SERVICE_ROLE_KEY}}
    # Override the image's healthcheck: it probes localhost, but the studio
    # server only binds the container IP (hence the service-name URL).
    healthcheck:
      test: ["CMD", "node", "-e", "fetch('http://studio:3000/api/platform/profile').then((r) => {{if (r.status !== 200) throw new Error(r.status)}})"]
      interval: 10s
      timeout: 10s
      retries: 6
      start_period: 30s

  # One-shot: loads schema, seed data, seed documents and auth users on the
  # first activation, then exits. Safe to re-run (skips an already provisioned
  # database). `restart: no` keeps compose from looping it.
  provision:
    image: {REGISTRY}/{app}/provision:__VERSION__
    restart: "no"
    depends_on:
      db:
        condition: service_healthy
      auth:
        condition: service_healthy
      storage:
        condition: service_healthy
      kong:
        condition: service_started
    environment:
      DB_URL: postgresql://supabase_admin:${{POSTGRES_PASSWORD}}@db:5432/postgres
      SUPABASE_URL: http://kong:8000
      SUPABASE_ANON_KEY: ${{ANON_KEY}}
      SUPABASE_SERVICE_ROLE_KEY: ${{SERVICE_ROLE_KEY}}
      UBK_VERSION: __VERSION__

volumes:
  db-data:
  storage-data:
"""
