"""Production artifacts for a 'proxy' kind model.

Generates <output>/prod/docker/: a single-container Caddy stack that terminates
HTTPS for `proxy.domain`, serves a static landing page (rendered from the
model's index.md) and reverse-proxies the listed app models by their base_uri.

Unlike the app stack (generators/prod), there is no Supabase and no React-Admin:
the deployed image is just Caddy with the built site and Caddyfile baked in. The
generated bin/prod-dc-* scripts publish/activate/remove it exactly like an app.
"""
import shutil
from pathlib import Path
from typing import Any, Dict

from ..prod.constants import REGISTRY
from . import caddyfile, landing

# Pinned Caddy image (single container: TLS + static + reverse proxy).
CADDY_IMAGE = "caddy:2.10-alpine"


class ProxyContext:
    def __init__(self, app_id: str, deployment_config: Dict[str, Any]):
        self.app_id = app_id  # output dir name: registry namespace and ~/ubk/<app_id>
        proxy = deployment_config["proxy"]
        self.domain = proxy["domain"]
        self.acme_email = proxy.get("acme_email")
        self.html_head_title = proxy["html_head_title"]
        # [{model, base_uri (trailing slash), port}], resolved by the CLI.
        self.targets = deployment_config["_proxy_targets"]


def generate(output_dir: Path, app_id: str, deployment_config: Dict[str, Any], model_dir: Path):
    ctx = ProxyContext(app_id, deployment_config)
    docker_dir = output_dir / "prod" / "docker"
    caddy_dir = docker_dir / "caddy"
    site_dir = caddy_dir / "site"

    # Whitelist .dockerignore: the image build uses the app root as context.
    _write(output_dir / ".dockerignore", """\
*
!prod/docker
prod/docker/docker-compose-*.yml
""")

    _write(docker_dir / "docker-compose.template.yml", _compose(ctx))
    _write(caddy_dir / "Dockerfile", _dockerfile())
    _write(caddy_dir / "Caddyfile", caddyfile.generate(ctx))

    # Landing page: index.md -> index.html, plus the assets/ tree.
    index_md = (model_dir / "index.md").read_text()
    _write(site_dir / "index.html", landing.render(index_md, ctx.html_head_title))

    assets_src = model_dir / "assets"
    assets_dst = site_dir / "assets"
    if assets_dst.exists():
        shutil.rmtree(assets_dst)
    if assets_src.is_dir():
        shutil.copytree(assets_src, assets_dst)


def _dockerfile() -> str:
    """Caddy image with the Caddyfile and static site baked in.

    Build context is the app output root (consistent with the app frontend image).
    """
    return f"""\
FROM {CADDY_IMAGE}
COPY prod/docker/caddy/Caddyfile /etc/caddy/Caddyfile
COPY prod/docker/caddy/site/ /srv/site/
"""


def _compose(ctx: ProxyContext) -> str:
    """Compose template deployed to ~/ubk/<app>/docker-compose-<version>.yml.

    bin/prod-dc-publish.py replaces __VERSION__. Caddy runs on the host network:
    it binds the host's port 443 directly and reaches app frontends via
    127.0.0.1:<port>. The caddy-data volume persists the ACME certificates and
    account across version switches.
    """
    return f"""\
# Production proxy stack for {ctx.app_id}, version __VERSION__ (immutable).
# Generated by UniBizKit; deployed by bin/prod-dc-up.py. Caddy terminates HTTPS
# for {ctx.domain} and reverse-proxies the app frontends published on the host.
# ACME certificates live in the caddy-data volume and survive version switches.
version: "2.4"

services:
  caddy:
    image: {REGISTRY}/{ctx.app_id}/caddy:__VERSION__
    restart: unless-stopped
    network_mode: host
    volumes:
      - caddy-data:/data
      - caddy-config:/config

volumes:
  caddy-data:
  caddy-config:
"""


def _write(path: Path, content: str):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
